export const STAFF_ASSIGNMENT_ERROR_CODES = {
  NO_STAFF_AVAILABLE: 'ORD_GROUP_NO_STAFF_AVAILABLE',
  STAFF_NOT_FOUND: 'ORD_GROUP_STAFF_NOT_FOUND',
  STAFF_INACTIVE: 'ORD_GROUP_STAFF_INACTIVE',
} as const;
