export const WAREHOUSE_ERROR_CODES = {
  WAREHOUSE_NOT_FOUND: 'WH_WAREHOUSE_NOT_FOUND',
  ZONE_NOT_FOUND: 'WH_ZONE_NOT_FOUND',
  INVALID_BIN_RANGE: 'WH_INVALID_BIN_RANGE',
  WAREHOUSE_CODE_IN_USE: 'WH_WAREHOUSE_CODE_IN_USE',
  ZONE_CODE_IN_USE: 'WH_ZONE_CODE_IN_USE',
} as const;
